### ISSUE TITLE
Docker image crashes

### ISSUE THREAD

**Issue by moppymopperson** [y-js/y-websockets-server#9]
Following the instructions in the README file, the Docker image builds, but crashes on startup.

```
> y-websockets-server@10.0.0-2 start /usr/src/app
> DEBUG=y*,-y:connector-message node ./src/server.js

module.js:341
    throw err;
    ^

Error: Cannot find module '../../yjs/y.node.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/src/app/src/server.js:5:11)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)

npm info lifecycle y-websockets-server@10.0.0-2~start: Failed to exec start script
npm ERR! Linux 4.9.87-linuxkit-aufs
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.12.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! y-websockets-server@10.0.0-2 start: `DEBUG=y*,-y:connector-message node ./src/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the y-websockets-server@10.0.0-2 start script 'DEBUG=y*,-y:connector-message node ./src/server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the y-websockets-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     DEBUG=y*,-y:connector-message node ./src/server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs y-websockets-server
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls y-websockets-server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log
```

**Comment by ryanismert** [comment]
You need to apply the fix here: https://github.com/y-js/yjs/issues/103. Also you probably want to change the dockerfile to ref ```node``` instead of the deprecated ```node:5-onboard```.

**Comment by dmonad** [comment]
Hey, thanks for the tip. I probably won't fix this since the new release will slowly running out. 
If you create a PR I'll happily accept it though

**Comment by napyk** [comment]
Im trying to get this version to work with Docker. I applied the fix mentioned above and use the latest node docker image. y-websockets-server starts fine, but on the first client connection the server crashes.

```Running y-websockets-server: port: 1234, redis: null 
  y-websockets-server User "tQ0NndaOre4jynijAAAA" joins room "richtext-example" +0ms
y:connector 2218000027: User joined tQ0NndaOre4jynijAAAA +0ms
y:connector User2218000027 to UsertQ0NndaOre4jynijAAAA: Send 'sync step 1' +21ms
/usr/src/y-websockets-server/node_modules/yjs/y.node.js:631
      throw new Error('Expected an ArrayBuffer or Uint8Array!')
      ^

Error: Expected an ArrayBuffer or Uint8Array!
    at new BinaryDecoder (/usr/src/y-websockets-server/node_modules/yjs/y.node.js:631:13)
    at Socket.<anonymous> (/usr/src/y-websockets-server/src/server.js:102:19)
    at Socket.emit (events.js:197:13)
    at /usr/src/y-websockets-server/node_modules/socket.io/lib/socket.js:514:12
    at processTicksAndRejections (internal/process/next_tick.js:74:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! y-websockets-server@10.0.0-3 start: `DEBUG=y*,-y:connector-message node ./src/server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the y-websockets-server@10.0.0-3 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-03-13T13_50_39_954Z-debug.log
```

When i get this to work I can make PR with a new Dockerfile and the applied fix.

Im using the module from npm (version 9.2.1) for now. This version works fine.
